### ISSUE TITLE
NoClassDefFoundError: net/kyori/text/Component

### ISSUE THREAD

**Issue by MiraculixxT** [N3FS/gChat#17]
Everytime velocity tries to enable the plugin, it says that i can not find  net/kyori/text/Component.
I use the latest version of velocity and gChat

https://www.toptal.com/developers/hastebin/geyusetipa.yaml

**Comment by mdcfe** [comment]
You're using an outdated Velocity 1.1.x build of gChat. These builds haven't been supported for over a year.

You need to build the main branch yourself and use that on Velocity 3.x.
