### ISSUE TITLE
Make links clickable

### ISSUE THREAD

**Issue by mdcfe** [N3FS/gChat#2]
From lucko/gChat#9, opened by @Magi1053:

> When I paste a link in the chat, I am unable to click it (using client 1.12.2). I thought it would be nice if it detected hyperlinks in the chat and automatically made them clickable.

I haven't touched this for a while, but `text` recently added [`legacyLinking`](https://github.com/lucko/gChat/issues/9#issuecomment-511186257).

**Comment by mdcfe** [comment]
Fixed in 630741 - you can download the latest build from [CircleCI](https://circleci.com/api/v1.1/project/github/N3FS/gChat/latest/artifacts/0/gChat-Velocity.jar).

**Comment by Magi1053** [comment]
I installed this update on my server, the links are still white plaintext (not formatted like a hyperlink).
Additionally, if you have a click event set in your gchat config, it overrides the hyperlink click event.

**Comment by mdcfe** [comment]
Link styles currently aren't implemented - I'll look into this when I can.

I'm away until August so I won't be able to look into the click event bug until I'm home.

**Comment by mdcfe** [comment]
Fixed in f75f096163650ae3999a4053fea7cc89ee2d3d07 - download the latest build from [CircleCI](https://circleci.com/api/v1.1/project/github/N3FS/gChat/latest/artifacts/0/gChat-Velocity.jar).
