### ISSUE TITLE
Artifact not found

### ISSUE THREAD

**Issue by requ1Re** [N3FS/gChat#9]
Hi,

 I am not really sure if this repository is still maintained... but if it is: I am not able to find any Artifacts to download. The link I found (https://circleci.com/api/v1.1/project/github/N3FS/gChat/latest/artifacts/0/gChat-Velocity.jar) seems to be dead.

Thanks

**Comment by mdcfe** [comment]
We don't have an active CI setup. If you've got JDK8 or newer installed, you can download the source code and run `gradlew build` to build a jar which you'll find in `target/libs`.

**Comment by jackmawer** [comment]
Here's a build of the latest master branch: https://archive.mawersoft.co.uk/mirror1/gChat-Velocity.jar

**Comment by mdcfe** [comment]
You can now download gChat-Velocity and gCV-Bridge from the [ender.zone build server](https://ci.ender.zone/view/Third%20Party%20Plugins).
